services:
  ds-postgres-dev:
    container_name: ds-postgres-dev
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: directory_service_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - ds-postgres-dev-data:/var/lib/postgresql/data
    networks:
      - ds-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  ds-seq-dev:
    container_name: ds-seq-dev
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "8080:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    restart: always
    volumes:
      - ds-seq-dev-data:/data
    networks:
      - ds-dev-network

  ds-redis-dev:
    container_name: ds-redis-dev
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ds-redis-dev-data:/data
    networks:
      - ds-dev-network
    restart: always

networks:
  ds-dev-network:
    driver: bridge
    name: ds-dev-network

volumes:
  ds-postgres-dev-data:
    name: ds-postgres-dev-data
  ds-seq-dev-data:
    name: ds-seq-dev-data
  ds-redis-dev-data:
    name: ds-redis-dev-data
