services:
  ds-backend-prod:
    container_name: ds-backend-prod
    build:
      context: .
      dockerfile: src/DirectoryService.Web/Dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_PASSWORD: ${NUGET_PASSWORD}
    ports:
      - "8090:8090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8090
    restart: always
    depends_on:
      - ds-postgres-prod
      - ds-seq-prod
      - ds-redis-prod

  ds-postgres-prod:
    container_name: ds-postgres-prod
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: directory_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - ds-postgres-prod-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ds-seq-prod:
    container_name: ds-seq-prod
    image: datalust/seq:latest
    ports:
      - "5343:5341"
      - "8082:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    restart: always
    volumes:
      - ds-seq-prod-data:/data

  ds-redis-prod:
    container_name: ds-redis-prod
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ds-redis-prod-data:/data
    networks:
      - ds-prod-network
    restart: always

networks:
  ds-prod-network:
    driver: bridge
    name: ds-prod-network

volumes:
  ds-postgres-prod-data:
    name: ds-postgres-prod-data
  ds-seq-prod-data:
    name: ds-seq-prod-data
  ds-redis-prod-data:
    name: ds-redis-prod-data
