services:
  directory-service:
    container_name: directory-service-prod
    build:
      context: .
      dockerfile: src/DirectoryService.Web/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8090
    restart: always
    depends_on:
      - postgres-prod
      - seq-prod
      - redis-prod
    
  postgres-prod:
    container_name: postgres-prod
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: directory_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq-prod:
    container_name: seq-prod
    image: datalust/seq:latest
    ports:
      - "5343:5341"
      - "8082:80"
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_FIRSTRUN_NOAUTHENTICATION: 'true'
    restart: always
    volumes:
      - seq-prod-data:/data
        
  redis-prod:
    container_name: redis-prod
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-prod-data:/data
    networks:
      - directory-prod-network
    restart: always        

networks:
  directory-prod-network:
    driver: bridge
    name: directory-prod-network

volumes:
  postgres-prod-data:
    name: postgres-prod-data
  seq-prod-data:
    name: seq-prod-data
  redis-prod-data:
    name: redis-prod-data
